// NOME PISCAR COM RITMO
// CURSO SIGNAL SPARK
// AUTOR JOSE LUIZ RYBARCZYK FILHO


// AQUI DEFINO A VARIAVEL LED_BUILTIN COMO SENDO A  PORTA 11 
#define LED_BUILTIN  11


// SETUP E A FUNCAO EXECUTADA UMA VEZ NA INICIALIZACAO DO SISTEMA
void setup(){
  // AQUI DEFINO A PORTA 11 COMO SAIDA
  pinMode(LED_BUILTIN, OUTPUT); 

}


// FUNCAO EXECUTADA REPETIDAMENTE ENQUANTO O SISTEMA ESTIVER LIGADO
void loop() {

// LACO DE REPETICAO QUE INCREMENTA 1 UNIDADE NA INTENSIDADE DO LED  
 for(int i = 0; i <= 255; i++){

  //A FUNCAO ANALOGWRITE CONTROLA A INTENSIDADE
  analogWrite(LED_BUILTIN, i);

  //AGUARDA UM INTERVALO DE TEMPO DE 10 MILISEGUNDOS
  delay(10);
 }

// LACO DE REPETICAO QUE DECREMENTA 1 UNIDADE NA INTENSIDADE DO LED
 for(int i = 255; i >= 0; i--){

  //A FUNCAO ANALOGWRITE CONTROLA A INTENSIDADE
  analogWrite(LED_BUILTIN, i);

  //AGUARDA UM INTERVALO DE TEMPO DE 10 MILISEGUNDOS
  delay(10);
 }
}
