// NOME PISCAR COM RITMO ALEATORIO
// CURSO SIGNAL SPARK
// AUTOR JOSE LUIZ RYBARCZYK FILHO

// AQUI DEFINO A VARIAVEL LED_BUILTIN COMO SENDO A PORTA 11 
#define LED_BUILTIN  11

// SETUP E A FUNCAO EXECUTADA UMA VEZ NA INICIALIZACAO DO SISTEMA
void setup(){
  // AQUI DEFINO A PORTA 11 COMO SAIDA
  pinMode(LED_BUILTIN, OUTPUT);

  // INICIALIZA O GERADOR DE NUMEROS ALEATORIOS
  randomSeed(analogRead(0));
}

// FUNCAO EXECUTADA REPETIDAMENTE ENQUANTO O SISTEMA ESTIVER LIGADO
void loop() {
  // GERA UM VALOR ALEATORIO PARA A INTENSIDADE DO LED (ENTRE 0 E 255)
  int intensidade = random(256);

  // GERA UM VALOR ALEATORIO PARA O TEMPO DE ESPERA (ENTRE 0 E 1000 MILISEGUNDOS)
  int tempoEspera = random(1001);

  // APLICA A INTENSIDADE ALEATORIA AO LED
  analogWrite(LED_BUILTIN, intensidade);

  // AGUARDA UM INTERVALO DE TEMPO ALEATORIO
  delay(tempoEspera);
}
